package com.hwf.blog.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blog
 */
public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.first_Picture
     *
     * @mbg.generated
     */
    private String firstPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.view_Count
     *
     * @mbg.generated
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.comment_Count
     *
     * @mbg.generated
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.is_Published
     *
     * @mbg.generated
     */
    private Boolean isPublished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.is_Commentabled
     *
     * @mbg.generated
     */
    private Boolean isCommentabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.create_Time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.update_Time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.first_Picture
     *
     * @return the value of blog.first_Picture
     *
     * @mbg.generated
     */
    public String getFirstPicture() {
        return firstPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.first_Picture
     *
     * @param firstPicture the value for blog.first_Picture
     *
     * @mbg.generated
     */
    public void setFirstPicture(String firstPicture) {
        this.firstPicture = firstPicture == null ? null : firstPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.flag
     *
     * @return the value of blog.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.flag
     *
     * @param flag the value for blog.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.view_Count
     *
     * @return the value of blog.view_Count
     *
     * @mbg.generated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.view_Count
     *
     * @param viewCount the value for blog.view_Count
     *
     * @mbg.generated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.comment_Count
     *
     * @return the value of blog.comment_Count
     *
     * @mbg.generated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.comment_Count
     *
     * @param commentCount the value for blog.comment_Count
     *
     * @mbg.generated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.is_Published
     *
     * @return the value of blog.is_Published
     *
     * @mbg.generated
     */
    public Boolean getIsPublished() {
        return isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.is_Published
     *
     * @param isPublished the value for blog.is_Published
     *
     * @mbg.generated
     */
    public void setIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.is_Commentabled
     *
     * @return the value of blog.is_Commentabled
     *
     * @mbg.generated
     */
    public Boolean getIsCommentabled() {
        return isCommentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.is_Commentabled
     *
     * @param isCommentabled the value for blog.is_Commentabled
     *
     * @mbg.generated
     */
    public void setIsCommentabled(Boolean isCommentabled) {
        this.isCommentabled = isCommentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.create_Time
     *
     * @return the value of blog.create_Time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.create_Time
     *
     * @param createTime the value for blog.create_Time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.update_Time
     *
     * @return the value of blog.update_Time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.update_Time
     *
     * @param updateTime the value for blog.update_Time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}